using System;
using System.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AsyncIt.Tests.IntegrationTests;

public class AsyncExternalTests
{

    [Fact]
    public void ShouldExtendNormalMethods()
    {
        var asyncAttr = new AsyncExternalAttribute(typeof(HttpClientTest), Interface.Sync);

        var newCode = nameof(HttpClientTest)
            .GetTypeInfo()
            .GenerateExtraCodeForExternalType(asyncAttr);

        Assert.Equal(
            """
            // <auto-generated/>
            public partial struct OrderService
            {
                public Task<Order> GetOrderAsync(int id) => Task.Run(() => GetOrder(id));
            }
            """, newCode);
    }

    [Fact]
    public void ShouldErrorIfExtendingStaticClass()
    {
    }
    [Fact]
    public void ShouldExtendGenericMethods()
    {
    }
}